### ISSUE TITLE
NullPointerException on load bundle with lost dependent bundle(s)

### ISSUE THREAD

**Issue by tmarkwardt** [eclipse/concierge#50]
on start a bündle with a lost dependent bündle i have a NullPointerException and not a BundleException

excample:
```
Concierge > start 6
java.lang.NullPointerException
        at org.eclipse.concierge.Concierge$CapabilityRegistry.getByValue(Concierge.java:5032)
        at org.eclipse.concierge.RFC1960Filter.filterWithIndex(RFC1960Filter.java:1147)
        at org.eclipse.concierge.Concierge$10.findProviders(Concierge.java:2488)
        at org.eclipse.concierge.Concierge$ResolverImpl.resolveResource(Concierge.java:3025)
        at org.eclipse.concierge.Concierge$ResolverImpl.resolveResource(Concierge.java:3199)
        at org.eclipse.concierge.Concierge$ResolverImpl.resolveResource(Concierge.java:3199)
        at org.eclipse.concierge.Concierge$ResolverImpl.resolveResource(Concierge.java:3199)
        at org.eclipse.concierge.Concierge$ResolverImpl.resolve0(Concierge.java:2836)
...

```
the bug i have found on class Concierge.CapatibilityRegistry (Package org.eclipse.concierge) on method getByValue() (line 5032 on version 5.0.0, but also on version 5.1.0):
`			final List<Capability> result = attributeIndex.get(value);
`
fixed:
`			final List<Capability> result = attributeIndex == null ? null : attributeIndex.get(value);
`
with the fixed code, i have correct Exception:
```
Concierge > start 6
org.osgi.framework.BundleException: Resolution failed [BundleRequirement{Import-Package org.osgi.service.event;version="[1.2,2)"}, BundleRequirement{Import-Pack
age org.osgi.service.cm;version="1.2.0"}]
        at org.eclipse.concierge.Concierge.resolve(Concierge.java:2648)
        at org.eclipse.concierge.BundleImpl$Revision.resolve(BundleImpl.java:1881)
        at org.eclipse.concierge.BundleImpl.activate(BundleImpl.java:532)
....
```

pleace fixing on code :-)

**Comment by tverbele** [comment]
Thanks for reporting. Maybe next time create a pull request which makes a quicker merge into the source tree.
