### ISSUE TITLE
PackageAdminImpl.getBundleType throws NullPointerException

### ISSUE THREAD

**Issue by svilenvul** [eclipse/concierge#59]
I have confirmed that the exception is still there with the latest Concierge snapshot that I could find - 5.1.0.SNAPSHOT-20180523024817.

The scenario is following:

- I trigger uninstallation of OSGi Deployment Package;
- Bundle Tracker is notified about the removed bundle and checks if the bundle is a fragment;
- NullPointerException occurs.

The `test-ext` deployment package contains a single bundle, which is not a fragment.

Logs:

```
Concierge> 13:28:56.638 ERROR org.eclipse.kura.deployment.agent.impl.DeploymentAgent[:360] - Exception uninstalling package test-ext
java.lang.NullPointerException: null
	at org.eclipse.concierge.compat.packageadmin.PackageAdminImpl.isFragment(PackageAdminImpl.java:374)
	at org.eclipse.concierge.compat.packageadmin.PackageAdminImpl.getBundleType(PackageAdminImpl.java:370)
	at org.eclipse.smarthome.core.internal.i18n.ResourceBundleTracker.isFragmentBundle(ResourceBundleTracker.java:144)
	at org.eclipse.smarthome.core.internal.i18n.ResourceBundleTracker.removedBundle(ResourceBundleTracker.java:85)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerRemoved(BundleTracker.java:491)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerRemoved(BundleTracker.java:414)
	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:449)
	at org.eclipse.concierge.Concierge.notifyBundleListeners(Concierge.java:3697)
	at org.eclipse.concierge.Concierge.notifyBundleListeners(Concierge.java:3632)
	at org.eclipse.concierge.BundleImpl.uninstall(BundleImpl.java:780)
	at org.apache.felix.deploymentadmin.spi.DropAllBundlesCommand.execute(DropAllBundlesCommand.java:48)
	at org.apache.felix.deploymentadmin.spi.DeploymentSessionImpl.call(DeploymentSessionImpl.java:73)
	at org.apache.felix.deploymentadmin.DeploymentAdminImpl.uninstallDeploymentPackage(DeploymentAdminImpl.java:352)
	at org.apache.felix.deploymentadmin.AbstractDeploymentPackage.uninstall(AbstractDeploymentPackage.java:296)
	at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.uninstaller(DeploymentAgent.java:347)
	at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.lambda$1(DeploymentAgent.java:178)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

If I understand correctly expected result is int or IllegalArgumentException - https://osgi.org/javadoc/r5/core/org/osgi/service/packageadmin/PackageAdmin.html#getBundleType(org.osgi.framework.Bundle)

I would really appreciate your assistance with this issue, please let me know if you need additional information.

**Comment by svilenvul** [comment]
Okay, I think I understand what happens. While the bundle is being uninstalled, current revision is set to null. After that listeners are notified about the changed state. 
In this case of this listeners checks the bundle type (which requires the already nullified current revision):

https://github.com/eclipse/concierge/blob/12ffabd79c37de8b67e1a63be66a8810cd1123f5/framework/org.eclipse.concierge/src/org/eclipse/concierge/BundleImpl.java#L775-L780

https://github.com/eclipse/concierge/blob/9399f771aa6b327612e45ce277c793929c1bbc2b/bundles/org.eclipse.concierge.service.packageadmin/src/org/eclipse/concierge/compat/packageadmin/PackageAdminImpl.java#L368-L371

https://github.com/eclipse/concierge/blob/9399f771aa6b327612e45ce277c793929c1bbc2b/framework/org.eclipse.concierge/src/org/eclipse/concierge/AbstractBundle.java#L238-L240

**Comment by svilenvul** [comment]
@JochenHiller, can you maybe take a look?

**Comment by rellermeyer** [comment]
Did not mean to close it. 

Svilen, I committed a fix. Could you please let me know if this works. 

I am not quite sure what the result of isFragment should be for an uninstalled bundle but at least it should not NPE anymore.

**Comment by svilenvul** [comment]
Thanks! I can confirm it is solved. 

Does the project have a public repository where I can download the latest snapshot version?
In the past I have used - http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/concierge/download/snapshots/, but it is out of date now.

**Comment by rellermeyer** [comment]
Great. 

Good question about the snapshots. @JochenHiller, do we have an issue with the CI?
