### ISSUE TITLE
Unable to start with Java 11

### ISSUE THREAD

**Issue by htreu** [eclipse/concierge#62]
Using OpenJDK 11 and the [Eclipse SmartHome Packaging Sample](https://github.com/eclipse/smarthome-packaging-sample) the concierge framework will not start up. This is the log output:

```
Using java: java
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
JAVA_VERSION=1101
JAVA_COMPACT_PROFILE=fulljre
JAVA_VENDOR=Oracle
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.eclipse.concierge.Concierge.<init>(Concierge.java:665)
	at org.eclipse.concierge.Factory.newFramework(Factory.java:33)
	at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsInputStream(XargsFileLauncher.java:79)
	at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsFile(XargsFileLauncher.java:70)
	at org.eclipse.concierge.Concierge.doMain(Concierge.java:606)
	at org.eclipse.concierge.Concierge.main(Concierge.java:525)
---------------------------------------------------------
  Concierge OSGi 5.0.0 on Mac OS X 10.14 starting ... (eclipse-smarthome) startlevel=3
---------------------------------------------------------
---------------------------------------------------------
  Framework started in 0.0 seconds.
---------------------------------------------------------
Exception in thread "main" org.osgi.framework.BundleException: Resolution failed [BundleRequirement {osgi.ee; filter:=(&(osgi.ee=JavaSE)(version=1.5))}]
	at org.eclipse.concierge.Concierge.resolve(Concierge.java:2645)
	at org.eclipse.concierge.BundleImpl$Revision.resolve(BundleImpl.java:1881)
	at org.eclipse.concierge.BundleImpl.activate(BundleImpl.java:532)
	at org.eclipse.concierge.BundleImpl.start(BundleImpl.java:506)
	at org.eclipse.concierge.BundleImpl.start(BundleImpl.java:444)
	at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsInputStream(XargsFileLauncher.java:169)
	at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsFile(XargsFileLauncher.java:70)
	at org.eclipse.concierge.Concierge.doMain(Concierge.java:606)
	at org.eclipse.concierge.Concierge.main(Concierge.java:525)
```

**Comment by rellermeyer** [comment]
Could you tell me what 
`  System.getProperty("java.specification.version")`
returns on your VM?

**Comment by htreu** [comment]
It returns `11`.

**Comment by rellermeyer** [comment]
Okay, thanks. 
I pushed a change that hopefully addresses the issue. Could you please check it out?
You can find the CI build here: https://ci.eclipse.org/concierge/job/Master_Build/296/

**Comment by rellermeyer** [comment]
Should be sufficient to swap out your existing concierge*.jar with framework/org.eclipse.concierge-5.1.0.SNAPSHOT-20181031093316-nodebug.jar from the build.
